name: Delivery

on:
  workflow_dispatch:

jobs:
  deliver:
    runs-on: macos-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version-file: pubspec.yaml
          channel: 'stable'
          cache: true

      - name: Install flutter dependencies
        shell: bash
        run: |
          flutter pub get

      - name: Get App Store Connect API Key
        run: |
             mkdir -p ./private_keys
             echo "${{ secrets.APP_STORE_CONNECT_API_KEY }}" > ./private_keys/AuthKey_${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}.p8

      - name: Build ios(xcarchive)
        run: |
          flutter build ios \
          --release \
          --no-codesign

      - name: Archive
        run: |
          xcodebuild archive \
            -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -sdk iphoneos \
            -archivePath build/ios/Runner.xcarchive \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Embed entitlements
        run: |
          codesign \
          --entitlements ios/Runner/Runner.entitlements \
          --force \
          --sign "-" build/ios/Runner.xcarchive/Products/Applications/Runner.app

      - name: Export Archive with ExportOptions.plist
        run: |
          xcodebuild -exportArchive \
            -archivePath build/ios/Runner.xcarchive \
            -exportOptionsPlist ios/ExportOptions.plist \
            -exportPath build/ios/ipa \
            -allowProvisioningUpdates \
            -authenticationKeyID ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }} \
            -authenticationKeyIssuerID ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }} \
            -authenticationKeyPath `pwd`/private_keys/AuthKey_${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}.p8
